import * as pc from "https://cdn.jsdelivr.net/npm/playcanvas@2.5.0/build/playcanvas.mjs";
const canvas=document.getElementById("application-canvas");
const app=new pc.Application(canvas,{graphicsDeviceOptions:{alpha:false,antialias:true,preserveDrawingBuffer:false}});
app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);app.setCanvasResolution(pc.RESOLUTION_AUTO);app.scene.ambientLight=new pc.Color(.42,.5,.62);
const sun=new pc.Entity("Alpine Sun");sun.addComponent("light",{type:"directional",color:new pc.Color(1,.94,.84),intensity:2.2,castShadows:true,shadowDistance:140,shadowResolution:1024});sun.setEulerAngles(38,-32,0);app.root.addChild(sun);app.scene.exposure=1.05;app.start();
const mats={};function mat(n,c,r=.8,m=0){const x=new pc.StandardMaterial();x.diffuse=new pc.Color(c[0],c[1],c[2]);x.roughness=r;x.metalness=m;x.useMetalness=true;x.name=n;x.update();mats[n]=x;return x}
const snow=mat("snow",[.88,.93,.96],.95),snow2=mat("sunlit snow",[.97,.98,1],.9),rock=mat("rock",[.25,.28,.3]),pine=mat("pine",[.035,.16,.105]),pine2=mat("pine tips",[.08,.28,.16]),wood=mat("dark timber",[.22,.12,.07]),roof=mat("roof",[.12,.07,.055]),glass=mat("windows",[.07,.22,.3],.18,.25),red=mat("red piste",[.62,.06,.045]),blue=mat("blue piste",[.04,.25,.68]),green=mat("green piste",[.08,.46,.18]),black=mat("black piste",[.06,.065,.075]),steel=mat("lift steel",[.34,.38,.42],.4,.8),chair=mat("chair",[.8,.08,.06],.55,.25),skin=mat("skin",[.72,.46,.32]),jacket=mat("jacket",[.08,.22,.58]),pants=mat("pants",[.04,.05,.07]),yellow=mat("sign",[.95,.63,.08]);
function entity(n,p,s,pos,m,parent){const e=new pc.Entity(n);e.addComponent("render",{type:p});e.setLocalScale(s[0],s[1],s[2]);e.setLocalPosition(pos[0],pos[1],pos[2]);e.render.material=m;(parent||app.root).addChild(e);return e}
const box=(n,s,p,m,q)=>entity(n,"box",s,p,m,q),sphere=(n,s,p,m,q)=>entity(n,"sphere",s,p,m,q),cyl=(n,s,p,m,q)=>entity(n,"cylinder",s,p,m,q),cone=(n,s,p,m,q)=>entity(n,"cone",s,p,m,q);
const W=150,D=110;
function height(x,z){return 2+25*Math.exp(-((x+32)**2/2888+(z-5)**2/3528))+17*Math.exp(-((x-28)**2/1568+(z+8)**2/2048))+15*Math.exp(-((x-4)**2/968+(z-34)**2/648))-9*Math.exp(-((x+3)**2/338+(z+18)**2/1800))+3*Math.sin(x*.11+z*.045)+2*Math.cos(z*.13-x*.04)}
function terrain(){const v=[],ix=[],N=62;for(let z=0;z<=N;z++)for(let x=0;x<=N;x++){const X=-75+150*x/N,Z=-55+110*z/N;v.push(X,height(X,Z),Z)}for(let z=0;z<N;z++)for(let x=0;x<N;x++){const i=z*(N+1)+x;ix.push(i,i+1,i+N+1,i+1,i+N+2,i+N+1)}const mesh=new pc.Mesh(app.graphicsDevice);mesh.setPositions(v);mesh.setIndices(ix);mesh.update(pc.PRIMITIVE_TRIANGLES);const e=new pc.Entity("Alpine Mountain");e.addComponent("render",{type:"asset"});e.render.meshInstances=[new pc.MeshInstance(mesh,snow)];app.root.addChild(e)}
terrain();
function tree(x,z,s){const y=height(x,z),e=new pc.Entity("Fir");e.setLocalPosition(x,y,z);app.root.addChild(e);cyl("trunk",[.22*s,.9*s,.22*s],[0,.45*s,0],wood,e);for(let i=0;i<3;i++)cone("foliage",[1.15*s,(2.4-i*.35)*s,1.15*s],[0,(1.25+i*.75)*s,0],i===2?pine2:pine,e)}
for(let i=0;i<95;i++){const x=-70+Math.random()*140,z=-48+Math.random()*90,y=height(x,z);if(y>4&&y<27&&Math.random()>.18)tree(x,z,.55+Math.random()*.75)}
function piste(n,pts,m,w){const root=new pc.Entity(n);app.root.addChild(root);for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),ang=Math.atan2(dx,dz)*180/Math.PI,y=(height(a[0],a[1])+height(b[0],b[1]))/2+.14,s=box(n+" section",[w,.12,len/2],[(a[0]+b[0])/2,y,(a[1]+b[1])/2],m,root);s.setLocalEulerAngles(0,ang,0)}}
const paths=[[[-37,32],[-32,20],[-25,10],[-16,1],[-8,-9],[0,-20]],[[25,31],[21,23],[16,15],[12,5],[8,-7],[5,-20]],[[-2,36],[4,27],[8,18],[13,9],[18,0],[20,-10]]];
piste("GREEN Meadow Run",paths[0],green,3.8);piste("RED Ridge Runner",paths[1],red,4.2);piste("BLUE Glacier Way",paths[2],blue,4);piste("BLACK Couloir",[[42,27],[35,20],[31,12],[27,2],[25,-10]],black,3.1);piste("BLUE Village Link",[[-24,-2],[-15,-9],[-8,-16],[2,-20],[14,-19]],blue,3.2);
function chalet(n,x,z,s){const y=height(x,z),e=new pc.Entity(n);e.setLocalPosition(x,y,z);e.setLocalScale(s,s,s);app.root.addChild(e);box("walls",[8,4.4,6],[0,2.2,0],wood,e);box("roof",[9.2,1.2,7.2],[0,5,0],roof,e);box("ridge",[9.5,.35,.35],[0,5.7,0],roof,e);for(const sx of[-3,3]){box("window",[1.7,1.35,.12],[sx,2.55,3.03],glass,e);box("window mullion",[.12,1.35,.15],[sx,2.55,3.12],yellow,e)}box("door",[1.1,2,.16],[0,1,3.06],wood,e);cyl("chimney",[.65,1.4,.65],[2.3,5.7,1.4],roof,e)}
chalet("Summit Lodge",-4,-24,1.3);chalet("Piste House",18,-16,.9);chalet("Mountain Hotel",-24,-15,1.25);
function station(n,x,z){const y=height(x,z),e=new pc.Entity(n);e.setLocalPosition(x,y,z);app.root.addChild(e);box("station",[5,3,4],[0,1.5,0],steel,e);box("roof",[6,.45,5],[0,3.1,0],roof,e);box("entry",[2,.1,.2],[0,.6,2.1],glass,e)}
function lift(n,a,b,count){const root=new pc.Entity(n);app.root.addChild(root);const ax=a[0],az=a[1],bx=b[0],bz=b[1],ay=height(ax,az)+3,by=height(bx,bz)+3,dx=bx-ax,dz=bz-az,len=Math.hypot(dx,dz),ang=Math.atan2(dx,dz);station(n+" base",ax,az);station(n+" summit",bx,bz);for(let i=1;i<7;i++){const t=i/7,x=ax+dx*t,z=az+dz*t,y=ay+(by-ay)*t;cyl(n+" tower",[.28,5,.28],[x,y-2.5,z],steel,root);box("crossarm",[3,.18,.3],[x,y,z],steel,root)}const cable=box("haul rope",[.07,.07,len],[(ax+bx)/2,(ay+by)/2,(az+bz)/2],steel,root);cable.setLocalEulerAngles(0,ang,Math.atan2(by-ay,len)*180/Math.PI);const carriers=[];for(let i=0;i<count;i++){const e=new pc.Entity(n+" chair "+i);root.addChild(e);e._phase=i/count;e._a=[ax,ay,az];e._b=[bx,by,bz];box("seat",[1.2,.18,.5],[0,-.55,0],chair,e);box("back",[1.2,.7,.12],[0,-.15,0],chair,e);box("hanger",[.08,1.5,.08],[0,.55,0],steel,e);carriers.push(e)}return carriers}
const lift1=lift("Eagle Express",[-4,-22],[-32,28],10),lift2=lift("Glacier Chair",[18,-15],[4,36],9),lift3=lift("Ridge Gondola",[27,-8],[43,29],7);
const guests=[];
function chooseRoute(g){const r=(g._route+1+Math.floor(Math.random()*2))%3;g._route=r;g._path=Math.random();}
function skier(i,x,z,type){const y=height(x,z)+.55,e=new pc.Entity(type+" "+i);e.setLocalPosition(x,y,z);app.root.addChild(e);sphere("helmet",[.28,.28,.28],[0,1.55,0],i%3===0?red:steel,e);sphere("head",[.23,.23,.23],[0,1.35,0],skin,e);box("body",[.38,.65,.28],[0,.9,0],i%2?jacket:red,e);box("legL",[.13,.55,.13],[-.12,.4,0],pants,e);box("legR",[.13,.55,.13],[.12,.4,0],pants,e);box("skiL",[.07,.05,.95],[-.17,.12,0],snow2,e);box("skiR",[.07,.05,.95],[.17,.12,0],snow2,e);if(type==="snowboarder")box("board",[.75,.06,.25],[0,.1,0],black,e);e._path=Math.random();e._route=Math.random()<.5?0:1;e._speed=.9+Math.random()*.8;guests.push(e)}
for(let i=0;i<36;i++){const r=i%3, t=(i/36+r*.31)%1, p=samplePath(paths[r],t); skier(i,p[0],p[1],i%6===0?"snowboarder":"skier"); guests[guests.length-1]._route=r; guests[guests.length-1]._path=t;}
let cash=250000,paused=false,weather=0;
function samplePath(path,t){const f=t*(path.length-1),i=Math.min(path.length-2,Math.floor(f)),q=f-i;return[path[i][0]+(path[i+1][0]-path[i][0])*q,path[i][1]+(path[i+1][1]-path[i][1])*q]}
app.on("update",dt=>{if(paused)return;guests.forEach((g,i)=>{g._path+=dt*g._speed*.018;if(g._path>=1){chooseRoute(g)} const p=samplePath(paths[g._route],g._path),p2=samplePath(paths[g._route],Math.min(1,g._path+.01));g.setLocalPosition(p[0],height(p[0],p[1])+.55,p[1]);g.setLocalEulerAngles(0,Math.atan2(p2[0]-p[0],p2[1]-p[1])*180/Math.PI,0)});lift1.concat(lift2,lift3).forEach(c=>{const t=(c._phase+performance.now()/1000*.035)%1;c.setPosition(pc.math.lerp(c._a[0],c._b[0],t),pc.math.lerp(c._a[1],c._b[1],t),pc.math.lerp(c._a[2],c._b[2],t))});document.getElementById("guests").textContent=String(26+Math.floor((performance.now()/1000)%140));document.getElementById("cash").textContent=Math.floor(cash).toLocaleString()});
let tool="select";document.querySelectorAll(".tool").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tool").forEach(x=>x.classList.remove("active"));b.classList.add("active");tool=b.dataset.tool;toast(tool==="select"?"Select and inspect your resort":"Build mode: "+b.textContent.trim())}));
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1600)}
document.getElementById("pauseBtn").onclick=()=>{paused=!paused;document.getElementById("pauseBtn").textContent=paused?"▶":"Ⅱ";toast(paused?"Game paused":"Game resumed")};
document.getElementById("weatherBtn").onclick=()=>{weather=(weather+1)%3;const n=["Clear","Snowfall","Storm"];document.getElementById("weather").textContent=n[weather];toast(n[weather]+" conditions")};
document.getElementById("resetBtn").onclick=()=>{cash=250000;toast("New season started")};
const camera=new pc.Entity("Camera");camera.addComponent("camera",{clearColor:new pc.Color(.52,.70,.84),fov:48});app.root.addChild(camera);let yaw=-28,pitch=38,distance=118,target=new pc.Vec3(0,14,2);function updateCamera(){const yr=yaw*Math.PI/180,pr=pitch*Math.PI/180;camera.setPosition(target.x+Math.sin(yr)*Math.cos(pr)*distance,target.y+Math.sin(pr)*distance,target.z+Math.cos(yr)*Math.cos(pr)*distance);camera.lookAt(target)}updateCamera();
const pointers=new Map();let lastDist=0;canvas.addEventListener("pointerdown",e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY])});canvas.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===1){yaw-=(e.clientX-old[0])*.22;pitch=Math.max(18,Math.min(78,pitch+(e.clientY-old[1])*.18));updateCamera()}else if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(lastDist)distance=Math.max(42,Math.min(135,distance-(d-lastDist)*.35));lastDist=d;updateCamera()}});canvas.addEventListener("pointerup",e=>{pointers.delete(e.pointerId);lastDist=0});canvas.addEventListener("wheel",e=>{distance=Math.max(42,Math.min(135,distance+e.deltaY*.06));updateCamera()},{passive:true});window.addEventListener("resize",()=>app.resizeCanvas(canvas.clientWidth,canvas.clientHeight));
setTimeout(()=>{document.getElementById("loading").style.opacity="0";setTimeout(()=>document.getElementById("loading").remove(),600);toast("Welcome to Summit Valley")},1400);